name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  build-test-version-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Bump version (minor)
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          npm version minor --no-git-tag-version

      e: Commit and push version bump
        run: |
          git add package.json package-lock.json
          git commit -m "ci: bump version [skip ci]" || echo "No changes to commit"
          git tag v$(node -p "require('./package.json').version")
          git push origin HEAD:main --tags

      - name: Publish to npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
